language: node_js
node_js:
  - lts/*
os:
  - linux
before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CHROME_BIN=chromium-browser ; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start ; fi
  - sleep 3 # give xvfb some time to start
addons:
  firefox: latest
